---
# https://github.com/perfectra1n/volsync/blob/main/helm/volsync/values.yaml

manageCRDs: true

fullNameOverride: volsync
nameOverride: volsync

metrics:
  disableAuth: true

image: &image
  repository: ghcr.io/perfectra1n/volsync
  tag: 0.17.6
kopia: *image
restic: *image

resources:
  requests:
    cpu: 50m
    memory: 64Mi
