---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json

hostname: &hostname cloudbeaver-10-242-20-170.lab-local.bichls.dev
scheme: https

defaultPodOptions:
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsUser: 1000

controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"
    pod:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
    containers:
      main:
        image:
          repository: dbeaver/cloudbeaver
          tag: 25.3.0
          pullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: &http 8978
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 1Gi
        probes:
          liveness:
            path: /status
            port: *http
          readiness:
            path: /status
            port: *http
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
              # config:
              #   image:
              #     repository: alpine
              #     tag: 3.22.2
              #     pullPolicy: IfNotPresent
              #   command:
              #     - sleep
              #     - infinity
              #   resources:
              #     requests:
              #       cpu: 10m
              #       memory: 20Mi
              #     limits:
              #       memory: 50Mi
              #   securityContext:
              #     readOnlyRootFilesystem: true
              #     allowPrivilegeEscalation: false
              #     capabilities:
              #       drop:
              #         - ALL

persistence:
  data:
    type: persistentVolumeClaim
    storageClass: openebs-mayastor
    accessMode: ReadWriteOnce
    size: 500Mi
    globalMounts:
      - path: /opt/cloudbeaver/workspace
  tmp:
    type: emptyDir
    sizeLimit: 50Mi
    globalMounts:
      - path: /home/ubuntu/.local/share/DBeaverData
      - path: /tmp/dbeaver
  api-token:
    type: persistentVolumeClaim
    storageClass: openebs-mayastor
    accessMode: ReadWriteOnce
    size: 500Mi
    globalMounts:
      - path: /opt/cloudbeaver/conf/keys

configMaps:
  main:
    includeInChecksum: true
    data:
      CLOUDBEAVER_DB_DRIVER: &db_driver sqlite_jdbc
      CLOUDBEAVER_DB_URL: &db_url jdbc:sqlite:/opt/cloudbeaver/workspace/cloudbeaver.db
      CLOUDBEAVER_DB_SCHEMA: cb
      CLOUDBEAVER_QM_DB_DRIVER: *db_driver
      CLOUDBEAVER_QM_DB_URL: *db_url
      CLOUDBEAVER_QM_DB_SCHEMA: qm
      CLOUDBEAVER_APP_ANONYMOUS_ACCESS_ENABLED: "false"
      CB_SERVER_URL: "{{ .Values.scheme }}://{{ .Values.hostname }}"

service:
  main:
    controller: main
    ports:
      http:
        port: *http
        targetPort: *http

route:
  main:
    annotations:
      argocd.argoproj.io/sync-options: Replace=true
    parentRefs:
      - name: traefik-internal
        namespace: traefik-system
        sectionName: https
    hostnames:
      - *hostname
    rules:
      - backendRefs:
          - identifier: main
            port: *http
        filters:
          - type: ExtensionRef
            extensionRef:
              group: traefik.io
              kind: Middleware
              name: oauth2
