---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json

hostname: &hostname kaneo-10-242-20-170.lab-local.bichls.dev
apiHostname: &api_hostname kaneo-api-10-242-20-170.lab-local.bichls.dev
scheme: https
registrationDisabled: "true"

controllers:
  api:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      main:
        image:
          repository: ghcr.io/usekaneo/api
          tag: 2.0.2
          pullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: &api_port 1337
        envFrom:
          - secret: kaneo-env
          - configMap: api
          - configMap: main
        probes:
          readiness:
            path: /me
            port: *api_port
            spec:
              initialDelaySeconds: 5
              periodSeconds: 10
          liveness:
            path: /me
            port: *api_port
            spec:
              initialDelaySeconds: 30
              periodSeconds: 10
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            memory: 512Mi

  web:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      main:
        image:
          repository: ghcr.io/usekaneo/web
          tag: 2.0.1
          pullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: &web_port 5173
        envFrom:
          - configMap: main
        probes:
          readiness:
            path: /
            port: *web_port
            spec:
              initialDelaySeconds: 5
              periodSeconds: 10
          liveness:
            path: /
            port: *web_port
            spec:
              initialDelaySeconds: 30
              periodSeconds: 10
        resources:
          requests:
            cpu: 20m
            memory: 32Mi
          limits:
            memory: 256Mi

configMaps:
  api:
    includeInChecksum: true
    data:
      DISABLE_REGISTRATION: "{{.Values.registrationDisabled}}"
  main:
    includeInChecksum: true
    data:
      KANEO_API_URL: "{{.Values.scheme}}://{{.Values.apiHostname}}"
      KANEO_CLIENT_URL: "{{.Values.scheme}}://{{.Values.hostname}}"
      CORS_ORIGINS: "{{.Values.scheme}}://{{.Values.hostname}}"

service:
  api:
    controller: api
    ports:
      http:
        port: *api_port
        targetPort: *api_port
  web:
    controller: web
    ports:
      http:
        port: *web_port
        targetPort: *web_port

route:
  api:
    annotations:
      argocd.argoproj.io/sync-options: Replace=true
    parentRefs:
      - name: traefik-internal
        namespace: traefik-system
        sectionName: https
    hostnames:
      - *api_hostname
    rules:
      - backendRefs:
          - identifier: api
            port: *api_port
            # matches:
            #   - path:
            #       type: PathPrefix
            #       value: /api
            # filters:
            #   - type: URLRewrite
            #     urlRewrite:
            #       path:
            #         type: ReplacePrefixMatch
            #         replacePrefixMatch: /
  web:
    annotations:
      argocd.argoproj.io/sync-options: Replace=true
    hostnames:
      - *hostname
    parentRefs:
      - name: traefik-internal
        namespace: traefik-system
        sectionName: https
    rules:
      - backendRefs:
          - identifier: web
            port: *web_port
        # matches:
        #   - path:
        #       type: PathPrefix
        #       value: /
