---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json

scheme: https
hostname: &hostname n8n.bichls.dev
tz: Asia/Bangkok

defaultPodOptions:
  securityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000

controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      main:
        image:
          repository: &image docker.n8n.io/n8nio/n8n
          tag: &tag 1.119.0
          pullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: &port 5678
        envFrom:
          - configMap: main
          - secret: n8n-env
        probes:
          liveness:
            path: /healthz
            port: *port
          readiness:
            path: /healthz/readiness
            port: *port
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 512Mi
        securityContext: &securityContext
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - ALL

  worker:
    containers:
      main:
        image:
          repository: *image
          tag: *tag
          pullPolicy: IfNotPresent
        args:
          - worker
          - --concurrency=5
        ports:
          - name: http
            containerPort: &worker_http 5678
        probes:
          liveness:
            path: /healthz
            port: *worker_http
          readiness:
            path: /healthz/readiness
            port: *worker_http
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 1Gi
        envFrom:
          - configMap: main
          - secret: n8n-env
        securityContext: *securityContext

  webhook:
    containers:
      main:
        image:
          repository: *image
          tag: *tag
          pullPolicy: IfNotPresent
        args:
          - webhook
        ports:
          - name: http
            containerPort: &webhook_http 5678
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz
                port: *webhook_http
          readiness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /healthz/readiness
                port: *webhook_http
            port: *webhook_http
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            memory: 512Mi
        envFrom:
          - configMap: main
          - secret: n8n-env
        securityContext: *securityContext

persistence:
  tmp:
    type: emptyDir
    globalMounts:
      - path: /home/node/.n8n
      - path: /home/node/.cache
    sizeLimit: 200Mi

configMaps:
  main:
    includeInChecksum: true
    data:
      N8N_EDITOR_BASE_URL: "{{.Values.scheme}}://{{.Values.hostname}}"
      N8N_HOST: "{{.Values.hostname}}"
      N8N_PROTOCOL: "{{.Values.scheme}}"
      WEBHOOK_URL: "{{.Values.scheme}}://{{.Values.hostname}}"
      N8N_LISTEN_ADDRESS: 0.0.0.0
      TZ: "{{.Values.tz}}"
      GENERIC_TIMEZONE: "{{.Values.tz}}"
      N8N_HIRING_BANNER_ENABLED: "false"
      N8N_DIAGNOSTICS_ENABLED: "false"
      N8N_PERSONALIZATION_ENABLED: "false"
      N8N_PROXY_HOPS: "1"
      # Security
      N8N_PUBLIC_API_SWAGGERUI_DISABLED: "true"
      N8N_PUBLIC_API_DISABLED: "true"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_BLOCK_ENV_ACCESS_IN_NODE: "true"
      # Task runners
      N8N_RUNNERS_ENABLED: "true"
      N8N_RUNNERS_BROKER_LISTEN_ADDRESS: 0.0.0.0
      # Queue mode
      OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: "true"
      N8N_DISABLE_PRODUCTION_MAIN_PROCESS: "true"
      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: n8n-redis
      QUEUE_BULL_REDIS_DB: "0"
      QUEUE_HEALTH_CHECK_ACTIVE: "true"
      # DB
      DB_TYPE: postgresdb
      DB_POSTGRESDB_DATABASE: n8n_production
      DB_POSTGRESDB_HOST: n8n-postgresql-rw
      DB_POSTGRESDB_PORT: "5432"
      # SMTP
      N8N_EMAIL_MODE: smtp
      N8N_SMTP_PORT: "587"
      N8N_SMTP_SSL: "false"
      N8N_SMTP_STARTTLS: "true"

service:
  main:
    controller: main
    ports:
      http:
        port: *port
        targetPort: *port
  webhook:
    controller: webhook
    ports:
      http:
        port: *webhook_http
        targetPort: *webhook_http

route:
  external:
    annotations:
      argocd.argoproj.io/sync-options: Replace=true
    parentRefs:
      - name: traefik-external
        namespace: traefik-system
        sectionName: https
    hostnames:
      - *hostname
    rules:
      - backendRefs: &webhook_backendRefs
          - identifier: webhook
            port: *webhook_http
        matches: &webhook_matches
          - path:
              type: PathPrefix
              value: /webhook/
      - backendRefs: &main_backendRefs
          - identifier: main
            port: *port
        matches:
          - path:
              type: PathPrefix
              value: /webhook-test/
      - backendRefs: *main_backendRefs
        matches:
          - path:
              type: PathPrefix
              value: /
        filters:
          - type: ExtensionRef
            extensionRef:
              group: traefik.io
              kind: Middleware
              name: oauth2
  internal:
    annotations:
      argocd.argoproj.io/sync-options: Replace=true
    parentRefs:
      - name: traefik-internal
        namespace: traefik-system
        sectionName: https
    hostnames:
      - n8n-10-242-20-170.lab-local.bichls.dev
    rules:
      - backendRefs: *webhook_backendRefs
        matches: *webhook_matches
      - backendRefs: *main_backendRefs
