---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: argocd
    namespace: argocd
    repo: oci://ghcr.io/argoproj/argo-helm
    name: argo-cd
    version: 9.1.8
    includeCRDs: true
    skipTests: true
    valuesFile: values.yaml

resources:
  - manifests/externalsecret.yaml
  - manifests/httproute.yaml
