---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: traefik
    namespace: traefik-system
    repo: oci://ghcr.io/traefik/helm
    name: traefik
    version: 37.4.0
    includeCRDs: true
    valuesFile: values.yaml

resources:
  - manifests/externalsecret.yaml
  - manifests/gateway-external.yaml
  - manifests/certificate.yaml
  - manifests/httproute-pve.yaml
  - manifests/httproute-filters.yaml
  - manifests/ingressroute-dashboard.yaml
  - manifests/middleware-geoblock.yaml
  - manifests/middleware-crowdsec.yaml
