---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: affine
    namespace: application
    repo: oci://ghcr.io/bjw-s-labs/helm
    name: app-template
    valuesFile: values.yaml
    version: 4.5.0

resources:
  - manifests/externalsecret.yaml
  - manifests/postgresql.yaml
  - manifests/redis.yaml
  - manifests/replicationsource.yaml

configMapGenerator:
  - name: affine-config
    namespace: application
    options:
      disableNameSuffixHash: true
    files:
      - configmaps/config.json

patches:
  - path: patches/job-migration.yaml
    target:
      kind: Job
      name: affine-migration
