---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json

hostname: &hostname note.bichls.dev

controllers:
  main:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      main:
        image:
          repository: &image ghcr.io/toeverything/affine
          tag: &tag 0.25.6
          pullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: &http 3010
        envFrom:
          - configMap: main
          - secret: affine-env
        probes:
          liveness:
            path: /info
            port: *http
          readiness:
            path: /info
            port: *http
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            memory: 1Gi
    initContainers:
      migration:
        image:
          repository: *image
          tag: *tag
          pullPolicy: IfNotPresent
        args:
          - node
          - ./scripts/self-host-predeploy.js
        envFrom:
          - configMap: main
          - secret: affine-env
        resources:
          requests:
            cpu: 20m
            memory: 64Mi
          limits:
            memory: 512Mi

configMaps:
  main:
    includeInChecksum: true
    data:
      REDIS_SERVER_HOST: affine-redis
      AFFINE_INDEXER_ENABLED: "false"

persistence:
  config:
    type: configMap
    name: affine-config
    globalMounts:
      - path: /root/.affine/config/config.json
        subPath: config.json
  secret:
    type: secret
    name: affine-env
    globalMounts:
      - path: /root/.affine/config/private.key
        subPath: private.key
  upload:
    type: persistentVolumeClaim
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: openebs-mayastor
    globalMounts:
      - path: /root/.affine/storage

service:
  main:
    controller: main
    ports:
      http:
        port: *http
        targetPort: *http

route:
  main:
    annotations:
      argocd.argoproj.io/sync-options: Replace=true
    parentRefs:
      - name: traefik-external
        namespace: traefik-system
        sectionName: https
    hostnames:
      - *hostname
    rules:
      - backendRefs:
          - identifier: main
            port: *http
        matches:
          - path:
              type: PathPrefix
              value: /admin
        filters:
          - type: ExtensionRef
            extensionRef:
              group: traefik.io
              kind: Middleware
              name: oauth2
      - backendRefs:
          - identifier: main
            port: *http
