---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: crowdsec
    namespace: crowdsec-system
    repo: https://crowdsecurity.github.io/helm-charts
    name: crowdsec
    valuesFile: values.yaml
    version: 0.22.0
    skipTests: true

resources:
  - manifests/externalsecret.yaml

configMapGenerator:
  - name: crowdsec-modsec-rules
    options:
      disableNameSuffixHash: true
    files:
      - modsecurity/crs.conf
