---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: cert-manager
    namespace: cert-manager
    releaseName: cert-manager
    repo: oci://quay.io/jetstack/charts
    valuesFile: values.yaml
    includeCRDs: true
    version: v1.19.4

resources:
  - manifests/selfsigned.yaml
  - manifests/letsencrypt.yaml
  - manifests/externalsecret.yaml
