---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - releaseName: external-secrets
    namespace: external-secrets
    repo: oci://ghcr.io/external-secrets/charts
    name: external-secrets
    version: 1.3.2
    includeCRDs: true
    valuesFile: values.yaml

resources:
  - manifests/certificate.yaml
  - manifests/clustersecretstore-bitwarden.yaml
